-- PostgreSQL
CREATE TABLE IF NOT EXISTS wish (
    id SERIAL PRIMARY KEY,
    from_user VARCHAR(45) NOT NULL,
    to_user VARCHAR(45) NOT NULL,
    email VARCHAR(255) NOT NULL,
    date_of_birth TIMESTAMP NOT NULL,
    wish_text VARCHAR(100) NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);